// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blogpb/blog.proto

package blogpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Blog struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	AuthodId             string   `protobuf:"bytes,4,opt,name=authod_id,json=authodId,proto3" json:"authod_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blog) Reset()         { *m = Blog{} }
func (m *Blog) String() string { return proto.CompactTextString(m) }
func (*Blog) ProtoMessage()    {}
func (*Blog) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cd072c3eda6f7ba, []int{0}
}

func (m *Blog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog.Unmarshal(m, b)
}
func (m *Blog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog.Marshal(b, m, deterministic)
}
func (m *Blog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog.Merge(m, src)
}
func (m *Blog) XXX_Size() int {
	return xxx_messageInfo_Blog.Size(m)
}
func (m *Blog) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog.DiscardUnknown(m)
}

var xxx_messageInfo_Blog proto.InternalMessageInfo

func (m *Blog) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Blog) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Blog) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Blog) GetAuthodId() string {
	if m != nil {
		return m.AuthodId
	}
	return ""
}

type NewBlogRequest struct {
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewBlogRequest) Reset()         { *m = NewBlogRequest{} }
func (m *NewBlogRequest) String() string { return proto.CompactTextString(m) }
func (*NewBlogRequest) ProtoMessage()    {}
func (*NewBlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cd072c3eda6f7ba, []int{1}
}

func (m *NewBlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewBlogRequest.Unmarshal(m, b)
}
func (m *NewBlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewBlogRequest.Marshal(b, m, deterministic)
}
func (m *NewBlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewBlogRequest.Merge(m, src)
}
func (m *NewBlogRequest) XXX_Size() int {
	return xxx_messageInfo_NewBlogRequest.Size(m)
}
func (m *NewBlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewBlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewBlogRequest proto.InternalMessageInfo

func (m *NewBlogRequest) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

type NewBlogResponse struct {
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewBlogResponse) Reset()         { *m = NewBlogResponse{} }
func (m *NewBlogResponse) String() string { return proto.CompactTextString(m) }
func (*NewBlogResponse) ProtoMessage()    {}
func (*NewBlogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cd072c3eda6f7ba, []int{2}
}

func (m *NewBlogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewBlogResponse.Unmarshal(m, b)
}
func (m *NewBlogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewBlogResponse.Marshal(b, m, deterministic)
}
func (m *NewBlogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewBlogResponse.Merge(m, src)
}
func (m *NewBlogResponse) XXX_Size() int {
	return xxx_messageInfo_NewBlogResponse.Size(m)
}
func (m *NewBlogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewBlogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewBlogResponse proto.InternalMessageInfo

func (m *NewBlogResponse) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

type ReadBlogRequest struct {
	BlodId               string   `protobuf:"bytes,1,opt,name=blod_id,json=blodId,proto3" json:"blod_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadBlogRequest) Reset()         { *m = ReadBlogRequest{} }
func (m *ReadBlogRequest) String() string { return proto.CompactTextString(m) }
func (*ReadBlogRequest) ProtoMessage()    {}
func (*ReadBlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cd072c3eda6f7ba, []int{3}
}

func (m *ReadBlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadBlogRequest.Unmarshal(m, b)
}
func (m *ReadBlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadBlogRequest.Marshal(b, m, deterministic)
}
func (m *ReadBlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadBlogRequest.Merge(m, src)
}
func (m *ReadBlogRequest) XXX_Size() int {
	return xxx_messageInfo_ReadBlogRequest.Size(m)
}
func (m *ReadBlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadBlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadBlogRequest proto.InternalMessageInfo

func (m *ReadBlogRequest) GetBlodId() string {
	if m != nil {
		return m.BlodId
	}
	return ""
}

type ReadBlogResponse struct {
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadBlogResponse) Reset()         { *m = ReadBlogResponse{} }
func (m *ReadBlogResponse) String() string { return proto.CompactTextString(m) }
func (*ReadBlogResponse) ProtoMessage()    {}
func (*ReadBlogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cd072c3eda6f7ba, []int{4}
}

func (m *ReadBlogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadBlogResponse.Unmarshal(m, b)
}
func (m *ReadBlogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadBlogResponse.Marshal(b, m, deterministic)
}
func (m *ReadBlogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadBlogResponse.Merge(m, src)
}
func (m *ReadBlogResponse) XXX_Size() int {
	return xxx_messageInfo_ReadBlogResponse.Size(m)
}
func (m *ReadBlogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadBlogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadBlogResponse proto.InternalMessageInfo

func (m *ReadBlogResponse) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

type ListBlogsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBlogsRequest) Reset()         { *m = ListBlogsRequest{} }
func (m *ListBlogsRequest) String() string { return proto.CompactTextString(m) }
func (*ListBlogsRequest) ProtoMessage()    {}
func (*ListBlogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cd072c3eda6f7ba, []int{5}
}

func (m *ListBlogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBlogsRequest.Unmarshal(m, b)
}
func (m *ListBlogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBlogsRequest.Marshal(b, m, deterministic)
}
func (m *ListBlogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBlogsRequest.Merge(m, src)
}
func (m *ListBlogsRequest) XXX_Size() int {
	return xxx_messageInfo_ListBlogsRequest.Size(m)
}
func (m *ListBlogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBlogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBlogsRequest proto.InternalMessageInfo

type ListBlogsResponse struct {
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBlogsResponse) Reset()         { *m = ListBlogsResponse{} }
func (m *ListBlogsResponse) String() string { return proto.CompactTextString(m) }
func (*ListBlogsResponse) ProtoMessage()    {}
func (*ListBlogsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cd072c3eda6f7ba, []int{6}
}

func (m *ListBlogsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBlogsResponse.Unmarshal(m, b)
}
func (m *ListBlogsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBlogsResponse.Marshal(b, m, deterministic)
}
func (m *ListBlogsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBlogsResponse.Merge(m, src)
}
func (m *ListBlogsResponse) XXX_Size() int {
	return xxx_messageInfo_ListBlogsResponse.Size(m)
}
func (m *ListBlogsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBlogsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBlogsResponse proto.InternalMessageInfo

func (m *ListBlogsResponse) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

func init() {
	proto.RegisterType((*Blog)(nil), "blog.Blog")
	proto.RegisterType((*NewBlogRequest)(nil), "blog.NewBlogRequest")
	proto.RegisterType((*NewBlogResponse)(nil), "blog.NewBlogResponse")
	proto.RegisterType((*ReadBlogRequest)(nil), "blog.ReadBlogRequest")
	proto.RegisterType((*ReadBlogResponse)(nil), "blog.ReadBlogResponse")
	proto.RegisterType((*ListBlogsRequest)(nil), "blog.ListBlogsRequest")
	proto.RegisterType((*ListBlogsResponse)(nil), "blog.ListBlogsResponse")
}

func init() {
	proto.RegisterFile("blogpb/blog.proto", fileDescriptor_1cd072c3eda6f7ba)
}

var fileDescriptor_1cd072c3eda6f7ba = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4d, 0x4b, 0xfb, 0x40,
	0x10, 0xc6, 0x49, 0xfe, 0xf9, 0xe7, 0x65, 0x0a, 0x7d, 0x19, 0xaa, 0x5d, 0x22, 0x88, 0xe4, 0x24,
	0x1e, 0x6a, 0x4d, 0x41, 0xf0, 0xe2, 0xa1, 0xb7, 0x82, 0x78, 0x88, 0x37, 0x2f, 0xd2, 0x64, 0x97,
	0xba, 0x10, 0xb2, 0xb1, 0xbb, 0xd5, 0xaf, 0xe7, 0x47, 0x93, 0x7d, 0x69, 0xad, 0xf1, 0x60, 0x4f,
	0xc9, 0xfc, 0xf6, 0x99, 0x7d, 0xe6, 0x59, 0x06, 0x46, 0x65, 0x2d, 0xd6, 0x6d, 0x79, 0xad, 0x3f,
	0xd3, 0x76, 0x23, 0x94, 0xc0, 0x40, 0xff, 0x67, 0x15, 0x04, 0x8b, 0x5a, 0xac, 0xb1, 0x0f, 0x3e,
	0xa7, 0xc4, 0xbb, 0xf0, 0x2e, 0x93, 0xc2, 0xe7, 0x14, 0xc7, 0xf0, 0x5f, 0x71, 0x55, 0x33, 0xe2,
	0x1b, 0x64, 0x0b, 0x24, 0x10, 0x55, 0xa2, 0x51, 0xac, 0x51, 0xe4, 0x9f, 0xe1, 0xbb, 0x12, 0xcf,
	0x20, 0x59, 0x6d, 0xd5, 0xab, 0xa0, 0x2f, 0x9c, 0x92, 0xc0, 0x9c, 0xc5, 0x16, 0x2c, 0x69, 0x36,
	0x83, 0xfe, 0x23, 0xfb, 0xd0, 0x3e, 0x05, 0x7b, 0xdb, 0x32, 0xa9, 0xf0, 0x1c, 0x8c, 0xbd, 0x31,
	0xec, 0xe5, 0x30, 0x35, 0x73, 0x19, 0x81, 0x1d, 0xeb, 0x06, 0x06, 0xfb, 0x0e, 0xd9, 0x8a, 0x46,
	0xb2, 0x3f, 0x5b, 0xae, 0x60, 0x50, 0xb0, 0x15, 0x3d, 0x74, 0x99, 0x40, 0x54, 0xd6, 0x76, 0x24,
	0x9b, 0x2c, 0xd4, 0xe5, 0x92, 0x66, 0x39, 0x0c, 0xbf, 0xb5, 0x47, 0xde, 0x8f, 0x30, 0x7c, 0xe0,
	0x52, 0x69, 0x22, 0x9d, 0x41, 0x36, 0x87, 0xd1, 0x01, 0x3b, 0xee, 0xa2, 0xfc, 0xd3, 0x83, 0x9e,
	0x2e, 0x9f, 0xd8, 0xe6, 0x9d, 0x57, 0x0c, 0x6f, 0x21, 0x72, 0x59, 0x71, 0x6c, 0xc5, 0x3f, 0x1f,
	0x2b, 0x3d, 0xe9, 0x50, 0xe7, 0x73, 0x07, 0xf1, 0x2e, 0x04, 0x3a, 0x49, 0xe7, 0x01, 0xd2, 0xd3,
	0x2e, 0x76, 0xad, 0xf7, 0x90, 0xec, 0xe7, 0x46, 0x27, 0xea, 0x86, 0x4b, 0x27, 0xbf, 0xb8, 0xed,
	0x9e, 0x79, 0x8b, 0xf8, 0x39, 0xb4, 0x0b, 0x55, 0x86, 0x66, 0x99, 0xe6, 0x5f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xd4, 0x1a, 0xc6, 0x13, 0x61, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BlogServiceClient is the client API for BlogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlogServiceClient interface {
	NewBlog(ctx context.Context, in *NewBlogRequest, opts ...grpc.CallOption) (*NewBlogResponse, error)
	ReadBlog(ctx context.Context, in *ReadBlogRequest, opts ...grpc.CallOption) (*ReadBlogResponse, error)
	ListBlogs(ctx context.Context, in *ListBlogsRequest, opts ...grpc.CallOption) (BlogService_ListBlogsClient, error)
}

type blogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlogServiceClient(cc grpc.ClientConnInterface) BlogServiceClient {
	return &blogServiceClient{cc}
}

func (c *blogServiceClient) NewBlog(ctx context.Context, in *NewBlogRequest, opts ...grpc.CallOption) (*NewBlogResponse, error) {
	out := new(NewBlogResponse)
	err := c.cc.Invoke(ctx, "/blog.BlogService/NewBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) ReadBlog(ctx context.Context, in *ReadBlogRequest, opts ...grpc.CallOption) (*ReadBlogResponse, error) {
	out := new(ReadBlogResponse)
	err := c.cc.Invoke(ctx, "/blog.BlogService/ReadBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) ListBlogs(ctx context.Context, in *ListBlogsRequest, opts ...grpc.CallOption) (BlogService_ListBlogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BlogService_serviceDesc.Streams[0], "/blog.BlogService/ListBlogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &blogServiceListBlogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BlogService_ListBlogsClient interface {
	Recv() (*ListBlogsResponse, error)
	grpc.ClientStream
}

type blogServiceListBlogsClient struct {
	grpc.ClientStream
}

func (x *blogServiceListBlogsClient) Recv() (*ListBlogsResponse, error) {
	m := new(ListBlogsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BlogServiceServer is the server API for BlogService service.
type BlogServiceServer interface {
	NewBlog(context.Context, *NewBlogRequest) (*NewBlogResponse, error)
	ReadBlog(context.Context, *ReadBlogRequest) (*ReadBlogResponse, error)
	ListBlogs(*ListBlogsRequest, BlogService_ListBlogsServer) error
}

// UnimplementedBlogServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBlogServiceServer struct {
}

func (*UnimplementedBlogServiceServer) NewBlog(ctx context.Context, req *NewBlogRequest) (*NewBlogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewBlog not implemented")
}
func (*UnimplementedBlogServiceServer) ReadBlog(ctx context.Context, req *ReadBlogRequest) (*ReadBlogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadBlog not implemented")
}
func (*UnimplementedBlogServiceServer) ListBlogs(req *ListBlogsRequest, srv BlogService_ListBlogsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListBlogs not implemented")
}

func RegisterBlogServiceServer(s *grpc.Server, srv BlogServiceServer) {
	s.RegisterService(&_BlogService_serviceDesc, srv)
}

func _BlogService_NewBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).NewBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/NewBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).NewBlog(ctx, req.(*NewBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_ReadBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).ReadBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/ReadBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).ReadBlog(ctx, req.(*ReadBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_ListBlogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListBlogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlogServiceServer).ListBlogs(m, &blogServiceListBlogsServer{stream})
}

type BlogService_ListBlogsServer interface {
	Send(*ListBlogsResponse) error
	grpc.ServerStream
}

type blogServiceListBlogsServer struct {
	grpc.ServerStream
}

func (x *blogServiceListBlogsServer) Send(m *ListBlogsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _BlogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blog.BlogService",
	HandlerType: (*BlogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewBlog",
			Handler:    _BlogService_NewBlog_Handler,
		},
		{
			MethodName: "ReadBlog",
			Handler:    _BlogService_ReadBlog_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListBlogs",
			Handler:       _BlogService_ListBlogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "blogpb/blog.proto",
}
